# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.5.2
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3307:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: exercise

  adminer:
    image: adminer:4.7.6
    restart: always
    ports:
      - 8080:8080
